insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Marietta Karolowski', '940 Westridge Road', '619 210 8129');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Jolee Vivash', '035 Monica Pass', '846 431 3684');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Tyrone Chelley', '62296 Fulton Point', '724 929 7426');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Lissi Eteen', '4165 Utah Court', '478 866 2135');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Libbie Goodsal', '245 Fairfield Alley', '298 431 3940');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Avrom Thornber', '815 Eastlawn Trail', '768 511 1018');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Alyse Mounfield', '7426 Nobel Park', '577 968 1895');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Yule Hallett', '50613 Cardinal Court', '595 956 2414');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Fabian Marshland', '75 Bartillon Road', '300 151 6377');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Jeniece Rosier', '6 Swallow Street', '727 357 2340');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Kennie Henke', '63677 Corry Crossing', '289 502 4547');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Melamie Ouchterlony', '11 Cambridge Place', '655 518 6181');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Derron Monroe', '01 Florence Point', '632 694 6355');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Herminia Bishopp', '45 Nevada Point', '745 503 9363');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Steve Shiels', '1125 Goodland Park', '628 537 2757');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Garey Eteen', '170 Tomscot Point', '958 206 8320');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Kirstin Reeday', '02745 Southridge Road', '288 709 4334');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Gail Pattington', '4 Elka Pass', '952 998 6354');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Mada Fitkin', '103 Cardinal Hill', '300 223 0856');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Briney Zima', '0 Meadow Vale Park', '252 679 3059');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Steven Boyfield', '8764 Butternut Parkway', '306 171 3784');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Karena Wombwell', '74 South Lane', '254 890 0476');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Kalvin Cromwell', '73 Redwing Parkway', '983 755 4278');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Tandie Iacavone', '8 Bashford Pass', '485 336 2800');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Christian Machin', '88 Rockefeller Hill', '939 798 2052');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Rip Po', '29 Fulton Plaza', '504 721 4277');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Rebecka Aitchison', '59 Leroy Hill', '555 860 5694');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Patty Jenkin', '7620 Main Road', '277 342 9998');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Jereme Giacobelli', '416 Hovde Avenue', '482 984 9422');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Blanca Cockrem', '85979 Kipling Trail', '518 849 6427');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Ozzie Brissenden', '5 Pine View Drive', '753 171 6493');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Allianora Blackaller', '441 Del Mar Street', '347 716 4923');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Estel Alesbrook', '6 Marcy Way', '233 489 6895');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Tab Heavy', '0 Mifflin Plaza', '996 940 7127');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Lavinia Maloney', '36201 Jenna Terrace', '921 532 7475');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Aldric Petrina', '49711 Kinsman Junction', '332 101 8061');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Kris Anglim', '74311 Chinook Lane', '281 724 8767');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Pearline Sweating', '43595 Rutledge Plaza', '577 929 3560');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Emmet Reglar', '73119 Loomis Road', '808 279 2974');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Gayleen Seyfart', '42710 Macpherson Avenue', '475 641 7346');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Zabrina Finlry', '2 Raven Terrace', '729 774 4279');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Nerte Gricks', '5 Towne Street', '213 571 2809');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Alric Desforges', '675 Westerfield Trail', '726 332 3226');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Maurizio de la Valette Parisot', '602 Derek Circle', '846 449 5060');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Horace Trusler', '63501 Birchwood Street', '887 299 2220');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Charlie Inchcomb', '7463 Pawling Court', '581 675 7750');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Fawne Ilden', '29 Vermont Pass', '606 383 5254');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Alasteir Rodolphe', '8627 Hallows Pass', '784 138 1198');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Baudoin Bru', '3 Novick Place', '213 502 8483');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Winnifred Shakeshaft', '14187 Caliangt Parkway', '422 417 7773');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Catha Duckers', '5881 Norway Maple Street', '769 164 7868');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Rikki Durward', '4163 Cottonwood Terrace', '747 642 3596');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Alex Cristofor', '2032 Annamark Way', '407 622 2753');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Coletta Coatts', '09 Meadow Vale Terrace', '914 707 3565');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Wynne Heffernan', '13486 Delaware Street', '906 193 0095');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Way Norville', '73158 Blue Bill Park Circle', '980 550 7864');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Jordain Plewright', '39341 Heath Park', '801 194 8514');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Helenka Kunz', '72335 Summit Circle', '719 899 5403');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Tiphani Myton', '975 Merrick Plaza', '156 577 8618');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Susi Kinch', '0986 Grover Lane', '527 545 2243');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Fonzie Cowup', '995 Burning Wood Hill', '130 809 0677');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Drona Cordero', '3 Lerdahl Circle', '786 853 2091');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Belinda Livoir', '03438 Glacier Hill Trail', '651 609 7033');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Donetta Lafflin', '5829 Truax Court', '864 990 9724');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Cchaddie Matiebe', '9 Carpenter Street', '791 684 6640');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Heddi Figgen', '26 Kingsford Drive', '818 810 7547');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Ingmar Wollers', '25826 Reindahl Terrace', '907 409 3817');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Julie Habgood', '6 Springview Circle', '513 139 3387');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Harmonia Frudd', '202 Spenser Road', '549 358 8522');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Antonino Stegel', '77821 Namekagon Alley', '537 608 7644');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Violetta Olfert', '084 Hoard Point', '867 422 0503');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Aaren Fausset', '7944 Crest Line Junction', '101 897 4385');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Rhonda Fligg', '65 Cordelia Street', '986 620 8844');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Malena Courtliff', '334 Reindahl Center', '100 603 3820');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Dodie Ware', '4782 Anhalt Drive', '298 619 0745');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Mina Dougherty', '50982 Debs Hill', '917 464 0410');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Clerissa Brokenshire', '0 Nova Avenue', '409 724 0551');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Imogene Bocking', '64 Hooker Court', '715 969 3019');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Ferdinanda Jovanovic', '9985 Gina Drive', '475 205 7346');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Trina Altham', '38021 Truax Terrace', '662 577 1534');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Liz Ortell', '72540 Veith Lane', '999 700 3410');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Tess Castletine', '89 Mockingbird Road', '323 907 2974');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Trent Solomonides', '20057 Stang Junction', '478 195 8817');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Eleanor Armell', '0 Old Shore Parkway', '134 179 3647');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Rica McLernon', '3387 Petterle Terrace', '117 300 5935');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Iona Roseburgh', '689 Stone Corner Avenue', '825 163 0813');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Rosaline Hulkes', '50056 Linden Plaza', '936 551 1428');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Rebekkah Nanetti', '450 Dixon Road', '798 281 3464');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Harli Kime', '167 Superior Drive', '877 548 4069');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Nobe Mewrcik', '17451 Thompson Center', '693 734 3391');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Dermot Owain', '648 Brown Point', '742 214 7440');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Beth Desson', '321 Brown Lane', '633 554 3951');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Lalo Casassa', '3989 Northwestern Parkway', '305 655 1714');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Flossy Drayson', '48 Nevada Pass', '790 939 8198');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Bernie Beeble', '4699 John Wall Trail', '537 605 6709');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Cal Sadd', '29 Southridge Way', '643 401 4713');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Fey Callway', '509 Barby Terrace', '193 228 4560');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Buck Applegarth', '777 Lyons Crossing', '713 228 6344');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Esmaria Whillock', '449 Clyde Gallagher Place', '914 535 1037');
insert into DOKTER (KDDOKTER, NAMADOKTER, ALAMATDOKTER, HPDOKTER) values ('''''', 'Ab Siseland', '3467 Westerfield Plaza', '271 355 1557');
