insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Methocarbamol', 22, 58395, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'Furosemide', 29, 105983, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'PCMX with Emollient', 57, 23457, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Saline Nasal', 29, 52234, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Natural herb', 75, 63355, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Naproxen', 79, 127461, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Torsemide', 1, 14227, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'Glycopyrrolate', 62, 68006, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'PurKlenz', 16, 122545, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'Haloperidol Decanoate', 11, 43626, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Degree', 49, 33277, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'B-PLEX 100', 86, 126049, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Conchae Argentum', 10, 97441, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Flumazenil', 87, 22819, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Bamboo Sap Patch', 36, 115345, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'SPF 25 UVA/UVB', 25, 123215, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'Senna laxative', 98, 122643, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', '3 CONCEPT EYES HONEY FACE CHIFFON FLUID 002', 73, 149690, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Bystolic', 38, 75009, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'CVS Gentle Laxative', 77, 130010, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'AGARICUS MUSCARIUS', 47, 32128, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Doxycycline Hyclate', 95, 26222, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'Clindacin P', 80, 82436, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'PRIME PRIMER CLASSIC', 91, 144710, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'COUMADIN', 77, 31022, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'CLE DE PEAU BEAUTE SILKY FOUNDATION I', 13, 140676, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Promethazine HCl', 87, 123194, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Savella', 42, 135452, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'Topicort', 89, 29451, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Glycerol-Saline Control', 52, 126263, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'CYSTARAN', 8, 71552, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'topiramate', 37, 17571, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'Azithromycin', 79, 102606, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'Treatment Set TS349573', 84, 131993, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'Epi-Clenz Instant Hand Antiseptic', 58, 121157, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Phenylephrine Hydrochloride', 74, 67258, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Alcohol', 5, 88402, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'Wellness Products VictoRx', 84, 66637, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'CRESTOR', 72, 18143, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Enoxaparin sodium', 22, 23287, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'BABOR Baborganic Crystal Face Scrub', 63, 10613, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'First Aid Antiseptic', 14, 55335, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Prednisone', 39, 71304, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Protonix', 11, 75659, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Fludeoxyglucose F 18', 94, 99049, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Meloxicam', 24, 23994, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Levetiracetam', 10, 102729, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'Ephedrine Sulfate', 33, 120654, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'pain relief', 28, 51515, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Divalproex Sodium', 27, 43074, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'Dulcolax', 88, 144904, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'MESNEX', 17, 13868, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'EXENCE WHITE', 2, 19304, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Skin Tag Relief', 6, 126945, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'NEXIUM', 84, 18994, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Antibacterial Hand GB Sugar Cookie', 7, 68398, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'Divalproex sodium', 64, 121504, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Sun Shades Lip Balm', 49, 31197, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Theophylline in Dextrose', 28, 12168, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Bupropion Hydrochloride', 87, 45948, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'Cholesterol HP', 80, 74067, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'sunmark fexofenadine hydrochloride', 67, 139604, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Alvesco', 38, 142290, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'Ambien CR', 18, 107599, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'LAMISIL', 28, 12620, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'butalbital, acetominophen and caffeine', 76, 13647, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Zithromax', 15, 23550, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'Ursodiol', 72, 109808, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'Tramadol Hydrochloride and Acetaminophen', 41, 95685, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'INVEGA SUSTENNA', 42, 145014, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Galantamine hydrobromide', 6, 50343, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'North Burn', 82, 137946, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Good Neighbor Pharmacy aspirin', 9, 26581, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'ipratropium bromide and albuterol sulfate', 4, 121628, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'Theophylline', 43, 149740, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'Atropine Sulfate', 81, 116140, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Anti-Bacterial Hand Sanitizer', 14, 113926, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'Treatment Set TS332131', 98, 147800, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'Good Sense Nicotine', 60, 137048, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Oxygen', 30, 36196, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'Red Cedar', 79, 60077, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'Escitalopram', 60, 92526, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Aspirin', 98, 106496, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'XANTHIUM STRUMARIUM VAR CANADENSE POLLEN', 100, 52735, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'EQUUS CABALLUS SKIN', 9, 78189, 'deskripsi2');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'NeutraCaine', 21, 26762, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Boils Eczema', 91, 41221, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'HAWAIIAN TROPIC', 64, 89474, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Topex', 71, 44063, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Atomoxetine Hydrochloride', 71, 76955, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'Natures Tears', 40, 62261, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Mupirocin Calcium', 64, 97042, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'Mercaptopurine', 64, 128672, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'KE1', 'MERREM', 82, 115970, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'Ponderosa Pine', 72, 149033, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'Famotidine', 50, 55413, 'deskripsi1');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'PONDS', 14, 44162, 'deskripsi4');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'BE1', 'Lysol', 9, 115436, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'TE1', 'BETULA NIGRA POLLEN', 44, 103933, 'deskripsi3');
insert into OBAT (KDOBAT, KDJENIS, NAMAOBAT, STOKOBAT, HARGAOBAT, DESKRIPSIOBAT) values (null, 'NA1', 'STERILE WATER', 86, 72260, 'deskripsi3');
